cask_args appdir: "~/Applications"

brew "asdf"
brew "diff-so-fancy"
brew "exa"
brew "fish"
brew "gh"
brew "git"
brew "git-extras"
brew "go"
brew "hugo"
brew "jq"
brew "neovim"
brew "rcm"
brew "trash"
brew "tree"

cask "1password"
cask "appcleaner"
cask "brave-browser"
cask "choosy"
cask "cleanshot"
cask "discord"
cask "figma"
cask "firefox"
cask "hyper"
cask "iterm2"
cask "ngrok"
cask "raycast"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"