cask_args appdir: "~/Applications"

brew "diff-so-fancy"
brew "eza"
brew "gh"
brew "git-extras"
brew "git"
brew "jq"
brew "mise"
brew "neovim"
brew "rcm"
brew "starship"
brew "trash"
brew "tree"
brew "zsh-syntax-highlighting"

cask "arc"
cask "bartender"
cask "1password"
cask "choosy"
cask "cleanshot"
cask "discord"
cask "figma"
cask "figma@beta"
cask "iterm2"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "visual-studio-code"
