format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$fill\
$nodejs\
$ruby\
$line_break\
$character"""

[directory]
style = "bold blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[nodejs]
symbol = "node "
format = '[$symbol($version) ]($style)'
style = "bold green"
version_format = "${major}.${minor}"

[ruby]
format = '[$symbol($version) ]($style)'
symbol = "ruby "
version_format = "${major}.${minor}"

[fill]
symbol = " "
