format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$nodejs\
$ruby\
$line_break\
$character"""

command_timeout = 1500

# use this so no nerd fonts are required
[nodejs]
symbol = "[⬢](bold green) "
